### ISSUE TITLE
Show information when a swosh link is opened on a computer.

### ISSUE THREAD

**Issue by Tejpbit** [Edholm/swosh#6]
Currently you get a blank page when the link is opened on a computer. Would be nice to be able to transfer the link to the phone. QR-code is the obvious way. But a general share button could also be nice.
And why not a "create your own swosh.me" to enable widen the use of the service.

**Comment by Edholm** [comment]
Something similar to this is already done, but I haven't deployed it yet due to some dependency issues. But I will fix it when I get around to it...

**Comment by Edholm** [comment]
Done as of latest commit. Reopen or create new issue if you're not satisfied with the solution.
